Repository Team-1-RAP/FSW-Frontend, pull requests merged in 2024-08, with the labels that each got.

#24 feat: update landing page and responsive mobile
  package-lock.json
  package.json
  src/assets/icons/landing-page/call.png
  src/assets/icons/landing-page/detail-rekening.png
  src/assets/icons/landing-page/email.png
  src/assets/icons/landing-page/kelola-uang.png
  src/assets/icons/landing-page/tarik-uang.png
  src/assets/icons/landing-page/transfer.png
  src/assets/icons/landing-page/virtual-acc.png
  src/assets/images/bg-pop-up.png
  src/assets/images/google-play.png
  src/assets/images/jumbotron-landing-page.png
  src/assets/images/logo-ikx.png
  src/components/fragments/LandingPage/Modal.tsx
  src/features/guests/LandingPage.tsx
  src/hooks/useSizeWindows.ts
Labels: enhancement

#42 fix: minor error class name on path svg
  src/features/guests/LandingPage.tsx
Labels: bug

#55 fix: correct missing path URL in API routing
  src/features/authentication/verifikasiRegister/uploadDocumentPage.tsx
Labels: bug

#56 fix: resolve issue with new user registration process
  package-lock.json
  package.json
  src/components/elements/file/FileUpload.tsx
  src/components/elements/form/FormRegister.tsx
  src/components/fragments/AccountType/index.tsx
  src/components/fragments/AccountType/type.ts
  src/components/fragments/LandingPage/Modal.tsx
  src/context/ResetValidationContext.tsx
  src/features/authentication/verifikasiRegister/finishPage.tsx
  src/features/authentication/verifikasiRegister/newPinPage.tsx
  src/features/authentication/verifikasiRegister/successPage.tsx
  src/features/authentication/verifikasiRegister/typeRekeningPage.tsx
  src/features/authentication/verifikasiRegister/uploadDocumentPage.tsx
  src/features/authentication/verifikasiRegister/verifyBiodataPage.tsx
  src/features/guests/LandingPage.tsx
  src/hooks/useFileUpload.ts
  src/router.tsx
  src/services/qrcodeService.ts
  src/services/uploadDocumentService.ts
  src/utils/fetchAccountPurpouse.ts
  src/utils/fetchAccountType.ts
  src/utils/fileUtils.ts
Labels: enhancement

#66 fix: error handling
  src/services/confirmTransferService.ts
Labels: bug, enhancement

#70 feat(auth): improve error handling for login attempts using API respo…
  src/services/authService.ts
Labels: enhancement

#71 fix: handle error when registration email or username is already taken
  src/components/fragments/Modal/index.tsx
  src/components/layouts/RegisterLayout.tsx
  src/features/authentication/RegisterPage.tsx
  src/features/authentication/verifikasiRegister/typeRekeningPage.tsx
  src/features/authentication/verifikasiRegister/uploadDocumentPage.tsx
  src/features/authentication/verifikasiRegister/verifyEmailPage.tsx
  src/services/registerService.ts
Labels: enhancement
